version: '3'

services:

  covid19https:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - covid19
    restart: always
    environment:
      DOMAINS: '${COVID19HOST} -> http://covid19:3838'
      STAGE: 'production' # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal

  covid19:
    image: philaris/covid19shiny:latest


volumes:
    https-portal-data: # to avoid re-signing when upgrading HTTPS-PORTAL
